# Generated by Django 3.0.2 on 2020-06-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('career_id', models.IntegerField(primary_key=True, serialize=False)),
                ('career', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'career',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=40, null=True)),
                ('basic_addr', models.CharField(blank=True, max_length=40, null=True)),
                ('detail_addr', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HolidayTpNm',
            fields=[
                ('holiday_tp_nm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('holiday_tp_nm', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'holiday_tp_nm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobsCd',
            fields=[
                ('jobs_cd', models.IntegerField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'jobs_cd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.IntegerField(primary_key=True, serialize=False)),
                ('license', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'license',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('sal_tp_nm', models.CharField(blank=True, max_length=40, null=True)),
                ('max_sal', models.IntegerField(blank=True, null=True)),
                ('min_sal', models.IntegerField(blank=True, null=True)),
                ('holiday_tp_nm', models.CharField(blank=True, max_length=40, null=True)),
                ('max_edubg', models.CharField(blank=True, max_length=20, null=True)),
                ('min_edubg', models.CharField(blank=True, max_length=20, null=True)),
                ('career', models.CharField(blank=True, max_length=40, null=True)),
                ('validation', models.CharField(blank=True, max_length=40, null=True)),
                ('wanted_info_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'notice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recom.User')),
                ('applieddate', models.DateTimeField(blank=True, db_column='appliedDate', null=True)),
            ],
            options={
                'db_table': 'favorite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recom.Notice')),
                ('reg_dt', models.CharField(blank=True, max_length=40, null=True)),
                ('close_dt', models.CharField(blank=True, max_length=40, null=True)),
                ('smodify_dt', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSpec',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recom.User')),
                ('user_spec_id', models.IntegerField()),
                ('edu_level', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WantedSpec',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recom.User')),
                ('wanted_spec_id', models.IntegerField()),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wanted_spec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCareer',
            fields=[
                ('user_spec', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recom.UserSpec')),
            ],
            options={
                'db_table': 'user_career',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLicense',
            fields=[
                ('user_spec', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recom.UserSpec')),
            ],
            options={
                'db_table': 'user_license',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WantedHolidayTpNm',
            fields=[
                ('wanted_spec', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recom.WantedSpec')),
            ],
            options={
                'db_table': 'wanted_holiday_tp_nm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WantedJobsCd',
            fields=[
                ('wanted_spec', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recom.WantedSpec')),
            ],
            options={
                'db_table': 'wanted_jobs_cd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WantedRegion',
            fields=[
                ('wanted_spec', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='recom.WantedSpec')),
            ],
            options={
                'db_table': 'wanted_region',
                'managed': False,
            },
        ),
    ]
